In [ ]:
import polars as pl
import matplotlib.pyplot as plt
import numpy as np

# KEY EDA to do

Project will involeve the flows too and from each user and we will look at binning the flows.

1) Basic checks
    Checks for duplicates number of source and destination computers, time window etc.
2) Frequency checks
    Checks for the distributions of user sent and recieved signal activity, frequency by human and machine.
3) Do basic statistical tests for periodicity across users and in human and machine users. (randomly sample if necessary)
4) investigate the effects of binning

list 2
1) Invesitgate the flows too and from each user how many go from each machine in a given time period.
2) Investigate variance of a machines flows over time.
3) Investigate the effect of binning width has on machine flow bias and variance.
4) Aim to indentify both human and machine operated accounts.
5) Static clustering

#### Ideas
- Idea smooth the distribution of mus towards the other distribution. I.e. for each user we will have a value of mu for each bin. Then for each cluster we will have an average distribution of mus. We will smooth the lower tail of the mu for a user towards the average lower tail obsered in that cluster. This way we preserve the periodic structure for each user whilst smoothing extremes.
- Pick binning based on frequency periodicity analysis.

#### Questions
- How to bin
- How to handle multiple requests within the same time period
- How to handle low frequency users
- How to smooth
- How good is the human machine classification system I have seen human users exhibiting behaviour with high requests and periodicity that are often seen in machines is this just a normal upper tail human or a machine
- Should I be dealing with users or computers
- What are the anonymous logons in the dataset

In [3]:
df = pl.scan_parquet("/home/ma/a/alb25/Project/thesis_code/data/raw/*")

In [4]:
df.head().collect()

shape: (5, 9)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ time ┆ source_use ┆ destinatio ┆ source_com ┆ … ┆ authentica ┆ logon_typ ┆ authentic ┆ success/f │
│ ---  ┆ r@domain   ┆ n_user@dom ┆ puter      ┆   ┆ tion_type  ┆ e         ┆ ation_ori ┆ ailure    │
│ str  ┆ ---        ┆ ain        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ entation  ┆ ---       │
│      ┆ str        ┆ ---        ┆ str        ┆   ┆ str        ┆ str       ┆ ---       ┆ str       │
│      ┆            ┆ str        ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C1250      ┆ … ┆ NTLM       ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C586       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C101$@DOM1 ┆ C101$@DOM1 ┆ C988       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│ 1    ┆ C1020$@DOM ┆ SYSTEM@C10 ┆ C1020      ┆ … ┆ Negotiate  ┆ Service   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 20         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C1021$@DOM ┆ C1021$@DOM ┆ C1021      ┆ … ┆ Kerberos   ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 1          ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

## Basic Checks

In [3]:
destinations = df.select('destination_computer').unique().collect()['destination_computer'].to_list()

In [4]:
sources = df.select('source_computer').unique().collect()['source_computer'].to_list()

In [ ]:
len(destinations)

15620

In [7]:
len(sources)

16006

In [ ]:
df.head().collect()

shape: (5, 9)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ time ┆ source_use ┆ destinatio ┆ source_com ┆ … ┆ authentica ┆ logon_typ ┆ authentic ┆ success/f │
│ ---  ┆ r@domain   ┆ n_user@dom ┆ puter      ┆   ┆ tion_type  ┆ e         ┆ ation_ori ┆ ailure    │
│ str  ┆ ---        ┆ ain        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ entation  ┆ ---       │
│      ┆ str        ┆ ---        ┆ str        ┆   ┆ str        ┆ str       ┆ ---       ┆ str       │
│      ┆            ┆ str        ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C1250      ┆ … ┆ NTLM       ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C586       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C101$@DOM1 ┆ C101$@DOM1 ┆ C988       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│ 1    ┆ C1020$@DOM ┆ SYSTEM@C10 ┆ C1020      ┆ … ┆ Negotiate  ┆ Service   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 20         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C1021$@DOM ┆ C1021$@DOM ┆ C1021      ┆ … ┆ Kerberos   ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 1          ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [53]:
df.select(
    pl.col('time').cast(pl.Int64).max().alias('max_time'),
    pl.col('time').cast(pl.Int64).min().alias('min_time'),
    ).collect()

shape: (1, 2)
┌──────────┬──────────┐
│ max_time ┆ min_time │
│ ---      ┆ ---      │
│ i64      ┆ i64      │
╞══════════╪══════════╡
│ 5011199  ┆ 1        │
└──────────┴──────────┘

In [ ]:
# We have 58 days of data
5011199 / (3600*24)

57.99998842592593

In [6]:
cols = df.collect_schema().names()
df = df.with_columns(pl.struct(cols).hash(seed=0).alias('hash'))
df2 = df.select('hash').group_by('hash').len().top_k(by='len', k=5).head().collect()

In [ ]:
# No duplicate rows found in the data
df2

shape: (5, 2)
┌──────────────────────┬─────┐
│ hash                 ┆ len │
│ ---                  ┆ --- │
│ u64                  ┆ u32 │
╞══════════════════════╪═════╡
│ 10489887825803446894 ┆ 1   │
│ 10043600765358434665 ┆ 1   │
│ 17312281700719399321 ┆ 1   │
│ 7365033346672452035  ┆ 1   │
│ 6629053896398302689  ┆ 1   │
└──────────────────────┴─────┘

## Human vs machine identification

In [6]:
df.head().collect()

shape: (5, 9)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ time ┆ source_use ┆ destinatio ┆ source_com ┆ … ┆ authentica ┆ logon_typ ┆ authentic ┆ success/f │
│ ---  ┆ r@domain   ┆ n_user@dom ┆ puter      ┆   ┆ tion_type  ┆ e         ┆ ation_ori ┆ ailure    │
│ str  ┆ ---        ┆ ain        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ entation  ┆ ---       │
│      ┆ str        ┆ ---        ┆ str        ┆   ┆ str        ┆ str       ┆ ---       ┆ str       │
│      ┆            ┆ str        ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C1250      ┆ … ┆ NTLM       ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ ANONYMOUS  ┆ ANONYMOUS  ┆ C586       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│      ┆ LOGON@C586 ┆ LOGON@C586 ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C101$@DOM1 ┆ C101$@DOM1 ┆ C988       ┆ … ┆ ?          ┆ Network   ┆ LogOff    ┆ Success   │
│ 1    ┆ C1020$@DOM ┆ SYSTEM@C10 ┆ C1020      ┆ … ┆ Negotiate  ┆ Service   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 20         ┆            ┆   ┆            ┆           ┆           ┆           │
│ 1    ┆ C1021$@DOM ┆ C1021$@DOM ┆ C1021      ┆ … ┆ Kerberos   ┆ Network   ┆ LogOn     ┆ Success   │
│      ┆ 1          ┆ 1          ┆            ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [8]:
source_users = df.select('source_user@domain').unique().collect()

In [10]:
source_users = source_users.to_series().to_list()

In [11]:
source_users

['C10010$@?',
 'C20627$@DOM1',
 'U1139@DOM1',
 'SYSTEM@C20114',
 'U2513@DOM9',
 'C26818$@?',
 'SYSTEM@C11866',
 'SYSTEM@C473',
 'ANONYMOUS LOGON@C20527',
 'U6706@?',
 'LOCAL SERVICE@C9976',
 'SYSTEM@C2363',
 'U10521@?',
 'ANONYMOUS LOGON@C10574',
 'C328$@DOM1',
 'U1389@?',
 'NETWORK SERVICE@C4593',
 'U5074@DOM9',
 'U5921@?',
 'NETWORK SERVICE@C10593',
 'U8061@DOM1',
 'U6347@DOM1',
 'U9410@DOM1',
 'U10613@DOM9',
 'C21313$@DOM1',
 'U6079@?',
 'ANONYMOUS LOGON@C1685',
 'C6236$@DOM1',
 'SYSTEM@C314',
 'C1272$@DOM1',
 'C18759$@?',
 'SYSTEM@C13455',
 'C1243$@DOM1',
 'ANONYMOUS LOGON@C5412',
 'LOCAL SERVICE@C4271',
 'ANONYMOUS LOGON@C15394',
 'LOCAL SERVICE@C2800',
 'C6151$@DOM1',
 'SYSTEM@C19094',
 'C450$@DOM1',
 'C7873$@DOM1',
 'U5167@DOM1',
 'NETWORK SERVICE@C18048',
 'C19280$@DOM1',
 'U6618@DOM9',
 'U1956@?',
 'U11168@DOM3',
 'C24122$@DOM1',
 'U6333@DOM9',
 'U12043@C24564',
 'NETWORK SERVICE@C7252',
 'ANONYMOUS LOGON@C17691',
 'U7505@DOM21',
 'SYSTEM@C12257',
 'SYSTEM@C20295',
 'U7363@C4810',
 'U8193@?',
 'LOCAL SERVICE@C21347',
 'U10670@?',
 'U5971@?',
 'SYSTEM@C7',
 'SYSTEM@C272',
 'U7883@DOM1',
 'ANONYMOUS LOGON@C10607',
 'SYSTEM@C1540',
 'SYSTEM@C12051',
 'U388@DOM9',
 'NETWORK SERVICE@C25908',
 'U4969@DOM9',
 'NETWORK SERVICE@C7999',
 'C26183$@DOM1',
 'ANONYMOUS LOGON@C4722',
 'C21469$@?',
 'U2687@?',
 'C25729$@DOM1',
 'U5565@DOM1',
 'NETWORK SERVICE@C20291',
 'ANONYMOUS LOGON@C2003',
 'LOCAL SERVICE@C23869',
 'U9550@DOM9',
 'U2338@DOM21',
 'LOCAL SERVICE@C26973',
 'C2161$@DOM1',
 'ANONYMOUS LOGON@C22179',
 'C20966$@DOM1',
 'U4668@?',
 'U2992@DOM1',
 'C3999$@DOM1',
 'C14482$@DOM1',
 'C18087$@DOM1',
 'ANONYMOUS LOGON@C1771',
 'LOCAL SERVICE@C11648',
 'C7798$@DOM1',
 'LOCAL SERVICE@C14212',
 'C15974$@DOM1',
 'U458@DOM1',
 'U6878@?',
 'C17068$@?',
 'SYSTEM@C93',
 'SYSTEM@C16650',
 'ANONYMOUS LOGON@C20398',
 'U2647@?',
 'C7041$@?',
 'C10555$@?',
 'U2035@C3433',
 'U6053@DOM1',
 'LOCAL SERVICE@C9793',
 'SYSTEM@C14692',
 'C9562$@DOM1',
 'U8816@?',
 'U9455@?',
 'C498$@?',
 'U7950@?',
 'SYSTEM@C14964',
 'ANONYMOUS LOGON@C17649',
 'NETWORK SERVICE@C24811',
 'U7130@DOM9',
 'ANONYMOUS LOGON@C18469',
 'U11489@DOM1',
 'SYSTEM@C6697',
 'LOCAL SERVICE@C23058',
 'C24599$@DOM1',
 'U1718@C23994',
 'C9704$@DOM1',
 'U8275@?',
 'U7363@C3260',
 'U7440@DOM1',
 'U5339@?',
 'C18388$@DOM1',
 'SYSTEM@C25754',
 'NETWORK SERVICE@C4142',
 'SYSTEM@C14216',
 'U8134@DOM1',
 'U8869@DOM1',
 'U1718@C22707',
 'ANONYMOUS LOGON@C8673',
 'SYSTEM@C8968',
 'U357@C39',
 'U8165@DOM1',
 'SYSTEM@C18121',
 'U1506@DOM9',
 'ANONYMOUS LOGON@C16896',
 'SYSTEM@C1051',
 'C16991$@C16991',
 'ANONYMOUS LOGON@C21583',
 'C16790$@DOM1',
 'SYSTEM@C22067',
 'U6856@C2626',
 'ANONYMOUS LOGON@C4429',
 'U4366@?',
 'C11470$@DOM1',
 'ANONYMOUS LOGON@C13360',
 'U7085@DOM1',
 'U3347@?',
 'U7718@?',
 'U1718@C24755',
 'C10931$@DOM1',
 'U8455@DOM1',
 'LOCAL SERVICE@C10031',
 'U5544@DOM1',
 'U10151@DOM1',
 'C14494$@DOM1',
 'U6817@DOM1',
 'U9662@?',
 'C25976$@C25976',
 'U5386@DOM1',
 'C6121$@DOM1',
 'U6125@?',
 'U8263@DOM1',
 'SYSTEM@C18466',
 'LOCAL SERVICE@C4167',
 'NETWORK SERVICE@C3407',
 'C16780$@DOM1',
 'C7235$@DOM1',
 'C19891$@DOM1',
 'C19428$@?',
 'SYSTEM@C25235',
 'C2290$@DOM1',
 'U4353@?',
 'LOCAL SERVICE@C21236',
 'SYSTEM@C21158',
 'NETWORK SERVICE@C12042',
 'ANONYMOUS LOGON@C12897',
 'U9834@DOM1',
 'LOCAL SERVICE@C4533',
 'U3727@DOM9',
 'U3444@DOM1',
 'U4750@DOM1',
 'ANONYMOUS LOGON@C3462',
 'U7400@?',
 'C24392$@DOM1',
 'U12015@DOM21',
 'ANONYMOUS LOGON@C7497',
 'SYSTEM@C21334',
 'U11695@DOM9',
 'LOCAL SERVICE@C4618',
 'C12613$@DOM1',
 'U1827@C4726',
 'ANONYMOUS LOGON@C10029',
 'U3217@?',
 'NETWORK SERVICE@C10175',
 'SYSTEM@C13007',
 'ANONYMOUS LOGON@C17100',
 'ANONYMOUS LOGON@C1999',
 'C3820$@DOM1',
 'U3983@DOM1',
 'SYSTEM@C4683',
 'ANONYMOUS LOGON@C913',
 'C6687$@DOM1',
 'C11004$@DOM1',
 'ANONYMOUS LOGON@C19520',
 'U7363@C3052',
 'SYSTEM@C2783',
 'ANONYMOUS LOGON@C22649',
 'ANONYMOUS LOGON@C22096',
 'ANONYMOUS LOGON@C7637',
 'ANONYMOUS LOGON@C8133',
 'U9535@DOM9',
 'SYSTEM@C21841',
 'ANONYMOUS LOGON@C23451',
 'C1526$@DOM1',
 'ANONYMOUS LOGON@C2911',
 'C2075$@DOM1',
 'C24014$@DOM1',
 'SYSTEM@C8147',
 'ANONYMOUS LOGON@C7511',
 'C25347$@DOM1',
 'U5067@DOM1',
 'C519$@DOM1',
 'U790@DOM9',
 'C2758$@DOM1',
 'U5328@?',
 'U1206@DOM1',
 'C10453$@DOM1',
 'C4285$@DOM1',
 'U7647@?',
 'ANONYMOUS LOGON@C521',
 'C9585$@DOM1',
 'SYSTEM@C9770',
 'ANONYMOUS LOGON@C763',
 'U1718@C23660',
 'U11623@DOM1',
 'C8316$@DOM1',
 'U1774@DOM1',
 'U5768@DOM1',
 'NETWORK SERVICE@C17269',
 'C19460$@DOM1',
 'SYSTEM@C4929',
 'ANONYMOUS LOGON@C2792',
 'U2086@DOM1',
 'U8606@DOM1',
 'SYSTEM@C20161',
 'U4962@?',
 'U2520@?',
 'C26812$@DOM1',
 'C11019$@DOM1',
 'ANONYMOUS LOGON@C14839',
 'C20287$@DOM1',
 'ANONYMOUS LOGON@C1789',
 'C4625$@DOM1',
 'C720$@DOM1',
 'U7362@C1811',
 'NETWORK SERVICE@C2436',
 'LOCAL SERVICE@C9279',
 'C7079$@DOM1',
 'C12929$@DOM1',
 'SYSTEM@C13062',
 'SYSTEM@C15758',
 'U6531@DOM1',
 'LOCAL SERVICE@C2714',
 'U6962@DOM9',
 'C7237$@DOM1',
 'U5714@DOM9',
 'U9497@?',
 'NETWORK SERVICE@C1624',
 'NETWORK SERVICE@C6881',
 'SYSTEM@C15572',
 'U5235@DOM9',
 'U1257@DOM1',
 'SYSTEM@C16399',
 'ANONYMOUS LOGON@C42',
 'U4606@?',
 'ANONYMOUS LOGON@C1261',
 'C10175$@DOM1',
 'U11413@DOM9',
 'U11510@DOM1',
 'C26610$@?',
 'ANONYMOUS LOGON@C7552',
 'U4329@?',
 'C16277$@DOM1',
 'C24886$@DOM1',
 'SYSTEM@C2308',
 'U3146@DOM1',
 'U8207@DOM21',
 'U9029@DOM1',
 'C23601$@DOM1',
 'U1875@DOM1',
 'C21780$@DOM1',
 'U7396@DOM9',
 'SYSTEM@C4835',
 'C9036$@?',
 'LOCAL SERVICE@C11238',
 'SYSTEM@C11499',
 'U6895@DOM1',
 'U9025@?',
 'U3251@?',
 'C24588$@DOM1',
 'C4251$@DOM1',
 'C8962$@DOM1',
 'C11741$@DOM1',
 'LOCAL SERVICE@C11774',
 'U11405@DOM1',
 'U11306@?',
 'NETWORK SERVICE@C4649',
 'U2473@DOM21',
 'U124@DOM1',
 'U668@?',
 'U8009@C3169',
 'ANONYMOUS LOGON@C8293',
 'SYSTEM@C19877',
 'C25253$@DOM1',
 'U9616@DOM9',
 'C6572$@DOM1',
 'SYSTEM@C20331',
 'C21902$@DOM51',
 'ANONYMOUS LOGON@C23062',
 'C316$@DOM1',
 'ANONYMOUS LOGON@C21621',
 'U6870@DOM1',
 'U11531@C4790',
 'ANONYMOUS LOGON@C21785',
 'C2658$@DOM1',
 'C6323$@DOM1',
 'U6028@DOM1',
 'U6657@?',
 'ANONYMOUS LOGON@C1965',
 'SYSTEM@C21778',
 'SYSTEM@C3134',
 'SYSTEM@C11912',
 'U3175@DOM1',
 'U1585@DOM1',
 'ANONYMOUS LOGON@C18583',
 'ANONYMOUS LOGON@C22903',
 'U9747@DOM1',
 'U7457@DOM1',
 'ANONYMOUS LOGON@C3631',
 'SYSTEM@C24603',
 'ANONYMOUS LOGON@C19967',
 'ANONYMOUS LOGON@C13214',
 'U9591@C25597',
 'U2960@DOM1',
 'C387$@DOM1',
 'ANONYMOUS LOGON@C19810',
 'U3174@DOM9',
 'SYSTEM@C26648',
 'U1418@DOM1',
 'ANONYMOUS LOGON@C15262',
 'U6184@?',
 'ANONYMOUS LOGON@C15978',
 'ANONYMOUS LOGON@C1337',
 'U1829@DOM9',
 'LOCAL SERVICE@C3344',
 'U2867@DOM1',
 'U6147@DOM1',
 'ANONYMOUS LOGON@C8109',
 'ANONYMOUS LOGON@C14055',
 'C18642$@?',
 'LOCAL SERVICE@C22227',
 'C7514$@DOM1',
 'SYSTEM@C1135',
 'U5947@DOM9',
 'U5934@DOM1',
 'U2024@DOM1',
 'NETWORK SERVICE@C1666',
 'NETWORK SERVICE@C16001',
 'U10362@DOM1',
 'U3029@?',
 'LOCAL SERVICE@C5061',
 'C16784$@DOM1',
 'NETWORK SERVICE@C3711',
 'ANONYMOUS LOGON@C16428',
 'U5428@?',
 'SYSTEM@C7962',
 'NETWORK SERVICE@C8818',
 'C25499$@DOM1',
 'ANONYMOUS LOGON@C21050',
 'U11542@C2382',
 'C15187$@?',
 'U672@C25071',
 'ANONYMOUS LOGON@C20496',
 'ANONYMOUS LOGON@C19324',
 'C7622$@DOM1',
 'U10008@DOM1',
 'U10305@C23421',
 'ANONYMOUS LOGON@C14796',
 'NETWORK SERVICE@C5991',
 'C7590$@DOM1',
 'SYSTEM@C12770',
 'LOCAL SERVICE@C7926',
 'SYSTEM@C19250',
 'C330$@DOM1',
 'U1386@DOM1',
 'NETWORK SERVICE@C4079',
 'U8150@?',
 'C2584$@DOM1',
 'NETWORK SERVICE@C8115',
 'SYSTEM@C22837',
 'C17458$@DOM1',
 'U9943@?',
 'ANONYMOUS LOGON@C27033',
 'U5909@?',
 'U12264@DOM9',
 'U73@DOM1',
 'SYSTEM@C1632',
 'U7021@DOM1',
 'C21014$@DOM1',
 'U2381@?',
 'ANONYMOUS LOGON@C520',
 'NETWORK SERVICE@C1832',
 'SYSTEM@C22298',
 'U453@C23474',
 'U2198@?',
 'SYSTEM@C9268',
 'U4190@DOM9',
 'U10326@DOM18',
 'C22580$@?',
 'U11636@DOM1',
 'U9061@DOM9',
 'U11787@?',
 'C353$@DOM1',
 'C11623$@DOM1',
 'U1856@DOM1',
 'ANONYMOUS LOGON@C1071',
 'C2430$@DOM1',
 'C23009$@DOM1',
 'LOCAL SERVICE@C5181',
 'U10524@DOM9',
 'U1223@?',
 'C8346$@?',
 'NETWORK SERVICE@C12614',
 'U9894@DOM21',
 'C10265$@?',
 'C12195$@DOM1',
 'ANONYMOUS LOGON@C12656',
 'U7020@DOM21',
 'U11415@DOM1',
 'U1899@DOM1',
 'SYSTEM@C83',
 'U7460@DOM1',
 'ANONYMOUS LOGON@C2740',
 'C4871$@DOM1',
 'U6198@?',
 'C25052$@DOM1',
 'NETWORK SERVICE@C5129',
 'NETWORK SERVICE@C2735',
 'U7363@C3386',
 'U11503@?',
 'SYSTEM@C4299',
 'U2064@DOM1',
 'U12195@DOM1',
 'U4713@?',
 'NETWORK SERVICE@C9426',
 'SYSTEM@C19655',
 'C13410$@?',
 'NETWORK SERVICE@C1846',
 'U8135@DOM1',
 'ANONYMOUS LOGON@C11408',
 'C1497$@DOM1',
 'C7654$@DOM1',
 'U3001@DOM1',
 'SYSTEM@C10819',
 'ANONYMOUS LOGON@C12484',
 'U9331@DOM1',
 'U4247@?',
 'C19206$@?',
 'NETWORK SERVICE@C11317',
 'U3409@DOM1',
 'U1732@DOM1',
 'SYSTEM@C20051',
 'U1289@DOM9',
 'U1702@C4804',
 'SYSTEM@C1174',
 'ANONYMOUS LOGON@C1254',
 'ANONYMOUS LOGON@C793',
 'U2959@DOM1',
 'C22774$@DOM1',
 'SYSTEM@C21242',
 'C10003$@DOM1',
 'ANONYMOUS LOGON@C21897',
 'SYSTEM@C444',
 'LOCAL SERVICE@C2663',
 'U4382@DOM9',
 'SYSTEM@C13014',
 'ANONYMOUS LOGON@C1532',
 'SYSTEM@C7244',
 'U10112@DOM1',
 'SYSTEM@C17624',
 'ANONYMOUS LOGON@C11139',
 'SYSTEM@C21583',
 'U11877@?',
 'SYSTEM@C25900',
 'SYSTEM@C9172',
 'C17757$@DOM1',
 'C22677$@DOM1',
 'U7112@?',
 'LOCAL SERVICE@C21583',
 'NETWORK SERVICE@C23505',
 'SYSTEM@C14629',
 'C13596$@DOM1',
 'U1989@DOM1',
 'U8380@DOM9',
 'SYSTEM@C3077',
 'C8180$@DOM1',
 'U4924@?',
 'ANONYMOUS LOGON@C24917',
 'SYSTEM@C8954',
 'SYSTEM@C6055',
 'U2411@DOM1',
 'U5247@?',
 'U5391@DOM1',
 'C21141$@DOM1',
 'ANONYMOUS LOGON@C797',
 'U5128@?',
 'ANONYMOUS LOGON@C342',
 'SYSTEM@C24597',
 'U6695@C423',
 'C14305$@DOM1',
 'C4273$@DOM1',
 'ANONYMOUS LOGON@C1165',
 'ANONYMOUS LOGON@C24857',
 'C16237$@DOM1',
 'U6112@DOM1',
 'ANONYMOUS LOGON@C10781',
 'SYSTEM@C23594',
 'SYSTEM@C24145',
 'LOCAL SERVICE@C12845',
 'C18658$@?',
 'ANONYMOUS LOGON@C18961',
 'C373$@DOM1',
 'SYSTEM@C24802',
 'ANONYMOUS LOGON@C3667',
 'C10672$@DOM1',
 'U9490@DOM1',
 'ANONYMOUS LOGON@C23055',
 'U8746@DOM9',
 'U9753@?',
 'SYSTEM@C26523',
 'U8893@DOM1',
 'C5355$@DOM1',
 'ANONYMOUS LOGON@C15207',
 'U2972@?',
 'SYSTEM@C8897',
 'U3922@?',
 'C20978$@?',
 'ANONYMOUS LOGON@C21631',
 'C11922$@DOM1',
 'SYSTEM@C10978',
 'U5080@DOM1',
 'SYSTEM@C1156',
 'ANONYMOUS LOGON@C9978',
 'U2380@DOM1',
 'ANONYMOUS LOGON@C14685',
 'U7185@DOM9',
 'ANONYMOUS LOGON@C14298',
 'SYSTEM@C22289',
 'U1718@C24984',
 'C10543$@DOM1',
 'SYSTEM@C12076',
 'LOCAL SERVICE@C1925',
 'C17445$@DOM1',
 'U10945@C1280',
 'U5480@?',
 'C8935$@DOM1',
 'ANONYMOUS LOGON@C2993',
 'C21019$@DOM1',
 'SYSTEM@C7491',
 'U9351@?',
 'U9584@?',
 'U9165@?',
 'U357@C1183',
 'SYSTEM@C24140',
 'ANONYMOUS LOGON@C2264',
 'U5169@?',
 'C13181$@DOM1',
 'C17752$@DOM1',
 'U4936@DOM21',
 'U5394@?',
 'U3280@DOM1',
 'U1718@C22778',
 'U4575@DOM1',
 'U8153@?',
 'ANONYMOUS LOGON@C867',
 'ANONYMOUS LOGON@C16158',
 'C78$@DOM1',
 'SYSTEM@C22909',
 'U1817@C1785',
 'C22980$@DOM1',
 'SYSTEM@C3387',
 'U8864@DOM1',
 'U5153@DOM1',
 'U76@?',
 'C7279$@?',
 'ANONYMOUS LOGON@C20846',
 'NETWORK SERVICE@C3094',
 'SYSTEM@C19348',
 'U9179@?',
 'U4817@DOM9',
 'ANONYMOUS LOGON@C8935',
 'U7877@lanl.gov',
 'ANONYMOUS LOGON@C11481',
 'C19253$@DOM1',
 'U4742@DOM1',
 'ANONYMOUS LOGON@C14451',
 'U7467@DOM1',
 'ANONYMOUS LOGON@C8621',
 'U220@DOM21',
 'ANONYMOUS LOGON@C19172',
 'C1385$@DOM1',
 'U393@DOM1',
 'U373@DOM1',
 'U2875@DOM1',
 'U3913@?',
 'C18215$@DOM1',
 'U2540@?',
 'U7198@DOM1',
 'U4695@?',
 'LOCAL SERVICE@C26057',
 'U3024@DOM1',
 'SYSTEM@C2866',
 'C1584$@DOM1',
 'SYSTEM@C11439',
 'U6115@DOM1',
 'C16120$@DOM1',
 'ANONYMOUS LOGON@C10520',
 'U4867@?',
 'U8257@DOM1',
 'U5707@DOM1',
 'U11156@?',
 'U3913@DOM9',
 'NETWORK SERVICE@C21000',
 'U7126@DOM9',
 'SYSTEM@C11553',
 'SYSTEM@C25560',
 'C21224$@DOM1',
 'ANONYMOUS LOGON@C13976',
 'U443@?',
 'ANONYMOUS LOGON@C26797',
 'SYSTEM@C5234',
 'ANONYMOUS LOGON@C14174',
 'U10402@?',
 'C6851$@DOM1',
 'C1199$@DOM1',
 'C2352$@DOM1',
 'U4082@?',
 'U1347@DOM9',
 'U7511@C1921',
 'C18315$@DOM1',
 'U7902@DOM1',
 'LOCAL SERVICE@C1719',
 'SYSTEM@C19299',
 'U7363@C1848',
 'U291@DOM1',
 'U5158@DOM1',
 'LOCAL SERVICE@C3417',
 'C9663$@DOM1',
 'C17254$@DOM1',
 'LOCAL SERVICE@C3386',
 'C5806$@DOM1',
 'C9317$@?',
 'U6840@DOM1',
 'SYSTEM@C16496',
 'NETWORK SERVICE@C18215',
 'U8640@DOM1',
 'U11859@DOM1',
 'SYSTEM@C9336',
 'U6308@DOM1',
 'C6497$@DOM1',
 'SYSTEM@C3770',
 'U1718@C23106',
 'C23683$@DOM1',
 'U2082@DOM9',
 'U3222@?',
 'U9786@?',
 'U3857@C7024',
 'NETWORK SERVICE@C7531',
 'NETWORK SERVICE@C8895',
 'U2782@DOM1',
 'SYSTEM@C971',
 'LOCAL SERVICE@C26320',
 'C4440$@DOM1',
 'C20524$@DOM1',
 'U372@?',
 'U2284@DOM1',
 'C16841$@DOM1',
 'SYSTEM@C3386',
 'SYSTEM@C6175',
 'ANONYMOUS LOGON@C15882',
 'LOCAL SERVICE@C4348',
 'U2184@DOM1',
 'C17052$@C17052',
 'C18144$@DOM1',
 'SYSTEM@C1043',
 'NETWORK SERVICE@C8359',
 'U6068@DOM9',
 'ANONYMOUS LOGON@C8257',
 'U937@?',
 'ANONYMOUS LOGON@C2527',
 'U7502@DOM21',
 'U5606@?',
 'C9838$@?',
 'U9700@?',
 'NETWORK SERVICE@C18277',
 'U6321@?',
 'U4514@DOM1',
 'ANONYMOUS LOGON@C560',
 'C14798$@DOM1',
 'SYSTEM@C25171',
 'ANONYMOUS LOGON@C12277',
 'NETWORK SERVICE@C5233',
 'ANONYMOUS LOGON@C6551',
 'C13789$@DOM1',
 'C19852$@DOM1',
 'ANONYMOUS LOGON@C20055',
 'U9813@DOM1',
 'C21746$@DOM1',
 'SYSTEM@C23623',
 'SYSTEM@C100',
 'C24610$@?',
 'ANONYMOUS LOGON@C10058',
 'ANONYMOUS LOGON@C21380',
 'ANONYMOUS LOGON@C11585',
 'U4922@?',
 'U1718@C25181',
 'C4537$@DOM1',
 'U1539@DOM1',
 'U10005@?',
 'SYSTEM@C18202',
 'NETWORK SERVICE@C25187',
 'C25888$@?',
 'U1844@?',
 'U7825@DOM9',
 'U8597@DOM1',
 'LOCAL SERVICE@C8068',
 'SYSTEM@C16397',
 'U4102@DOM1',
 'U8304@DOM9',
 'C18854$@DOM1',
 'U7182@?',
 'SYSTEM@C5467',
 'ANONYMOUS LOGON@C5277',
 'LOCAL SERVICE@C14655',
 'LOCAL SERVICE@C3787',
 'NETWORK SERVICE@C10314',
 'ANONYMOUS LOGON@C4711',
 'C6085$@DOM1',
 'U5868@DOM1',
 'C22149$@DOM1',
 'SYSTEM@C10181',
 'C9293$@?',
 'U2774@?',
 'ANONYMOUS LOGON@C21734',
 'U6968@DOM9',
 'C18861$@DOM1',
 'SYSTEM@C20271',
 'SYSTEM@C9034',
 'ANONYMOUS LOGON@C9436',
 'LOCAL SERVICE@C24750',
 'SYSTEM@C23600',
 'C20542$@DOM1',
 'U3941@DOM9',
 'NETWORK SERVICE@C3088',
 'U142@DOM1',
 'U12120@DOM1',
 'C1782$@DOM1',
 'SYSTEM@C12071',
 'SYSTEM@C9970',
 'C4726$@DOM1',
 'U8323@DOM1',
 'U6098@?',
 'C3522$@DOM1',
 'C43$@DOM1',
 'C18720$@DOM1',
 'LOCAL SERVICE@C19339',
 'NETWORK SERVICE@C14734',
 'U9773@DOM1',
 'U7363@C1603',
 'LOCAL SERVICE@C21093',
 'U570@?',
 'U972@?',
 'C1989$@DOM1',
 'U1359@DOM1',
 'C10589$@DOM1',
 'SYSTEM@C1355',
 'C17954$@DOM1',
 'U9714@?',
 'ANONYMOUS LOGON@C4983',
 'U9324@DOM21',
 'NETWORK SERVICE@C12979',
 'U6494@DOM1',
 'SYSTEM@C4479',
 'SYSTEM@C17581',
 'C20602$@DOM1',
 'C21229$@DOM1',
 'U6858@?',
 'SYSTEM@C18949',
 'LOCAL SERVICE@C24193',
 'C20844$@DOM1',
 'U8689@C19466',
 'U5348@DOM9',
 'C11496$@DOM1',
 'U1032@DOM9',
 'ANONYMOUS LOGON@C23446',
 'SYSTEM@C24315',
 'ANONYMOUS LOGON@C755',
 'U2229@?',
 'C259$@DOM1',
 'U5776@DOM1',
 'ANONYMOUS LOGON@C5233',
 'U10347@DOM1',
 'U8939@DOM9',
 'U6569@?',
 'C7268$@DOM1',
 'U5435@C10083',
 'U1943@DOM9',
 'C24548$@DOM1',
 'ANONYMOUS LOGON@C16860',
 'U5238@DOM1',
 'U3814@?',
 'C20216$@DOM1',
 'NETWORK SERVICE@C16492',
 'U825@?',
 'ANONYMOUS LOGON@C19795',
 'U4440@DOM1',
 'U6113@?',
 'SYSTEM@C2606',
 'U1718@C25343',
 'SYSTEM@C7420',
 'SYSTEM@C10772',
 'U3251@DOM9',
 'C3290$@?',
 'U7372@DOM1',
 'C20969$@DOM1',
 'SYSTEM@C19690',
 'ANONYMOUS LOGON@C356',
 'U4696@DOM1',
 'U10239@C21635',
 'U1718@C22081',
 'ANONYMOUS LOGON@C20082',
 'NETWORK SERVICE@C11174',
 'SYSTEM@C23381',
 'U11015@DOM1',
 'U9274@DOM1',
 'U2889@DOM1',
 'ANONYMOUS LOGON@C5971',
 'ANONYMOUS LOGON@C22081',
 'U2027@DOM9',
 'SYSTEM@C7318',
 'C2183$@DOM1',
 'C3094$@DOM1',
 'U2800@DOM1',
 'C10732$@DOM1',
 'ANONYMOUS LOGON@C8032',
 'SYSTEM@C13285',
 'U11104@DOM9',
 'C26388$@?',
 'C1055$@DOM1',
 'SYSTEM@C18835',
 'ANONYMOUS LOGON@C20787',
 'C9992$@DOM1',
 'U9292@DOM21',
 'U3084@DOM1',
 'C9535$@DOM1',
 'U11743@?',
 'ANONYMOUS LOGON@C22546',
 'SYSTEM@C1736',
 'U5499@?',
 'SYSTEM@C27066',
 'ANONYMOUS LOGON@C11321',
 'U5826@DOM1',
 'SYSTEM@C18896',
 'U1229@DOM1',
 'ANONYMOUS LOGON@C5443',
 'SYSTEM@C627',
 'C9666$@DOM1',
 'U12043@C7113',
 'LOCAL SERVICE@C13913',
 'C14891$@DOM1',
 'C8601$@DOM1',
 'ANONYMOUS LOGON@C16125',
 'U5693@?',
 'SYSTEM@C23246',
 'C532$@DOM1',
 'NETWORK SERVICE@C5371',
 'ANONYMOUS LOGON@C14381',
 'ANONYMOUS LOGON@C16345',
 'SYSTEM@C8310',
 'ANONYMOUS LOGON@C13266',
 'ANONYMOUS LOGON@C19254',
 'SYSTEM@C7268',
 'C8739$@DOM1',
 'SYSTEM@C19197',
 'SYSTEM@C18469',
 'SYSTEM@C11380',
 'U633@?',
 'C22921$@DOM1',
 'U4969@?',
 'LOCAL SERVICE@C24231',
 'SYSTEM@C25391',
 'ANONYMOUS LOGON@C5398',
 'U10255@DOM9',
 'U765@DOM1',
 'C26771$@DOM1',
 'U7315@?',
 'U1106@?',
 'SYSTEM@C2626',
 'SYSTEM@C8738',
 'SYSTEM@C5799',
 'C18170$@DOM1',
 'LOCAL SERVICE@C4803',
 'ANONYMOUS LOGON@C9683',
 'ANONYMOUS LOGON@C25905',
 'LOCAL SERVICE@C16247',
 'ANONYMOUS LOGON@C6485',
 'ANONYMOUS LOGON@C16332',
 'C16424$@DOM1',
 'SYSTEM@C18369',
 'U1718@C24972',
 'C2133$@?',
 'ANONYMOUS LOGON@C13105',
 'U2983@?',
 'U11698@DOM1',
 'C17546$@DOM1',
 'U12384@?',
 'NETWORK SERVICE@C4660',
 'ANONYMOUS LOGON@C11348',
 'U10215@C17465',
 'C5641$@DOM1',
 'U4998@DOM9',
 'C18294$@DOM1',
 'LOCAL SERVICE@C8131',
 'ANONYMOUS LOGON@C2473',
 'U7627@DOM1',
 'SYSTEM@C26732',
 'ANONYMOUS LOGON@C4264',
 'ANONYMOUS LOGON@C23871',
 'C875$@DOM1',
 'U5577@DOM1',
 'C10189$@?',
 'C16922$@DOM1',
 'C20877$@DOM1',
 'U5397@?',
 'U1718@C24348',
 'ANONYMOUS LOGON@C4167',
 'C17109$@?',
 'U8050@DOM1',
 'LOCAL SERVICE@C20476',
 'ANONYMOUS LOGON@C8045',
 'U4904@DOM9',
 'ANONYMOUS LOGON@C16732',
 'U7209@DOM1',
 'SYSTEM@C12875',
 'SYSTEM@C1799',
 'C23350$@DOM1',
 'C23845$@DOM1',
 'ANONYMOUS LOGON@C347',
 'C24055$@DOM1',
 'C15485$@DOM1',
 'C20274$@DOM1',
 'SYSTEM@C4702',
 'SYSTEM@C8186',
 'U5903@?',
 'C3155$@DOM1',
 'SYSTEM@C8017',
 'C5096$@DOM1',
 'C6590$@DOM1',
 'C6878$@DOM1',
 'C7507$@?',
 'C15403$@DOM1',
 'ANONYMOUS LOGON@C13095',
 'U5492@?',
 'SYSTEM@C16916',
 'LOCAL SERVICE@C20059',
 'C16206$@DOM1',
 'U5044@DOM1',
 'U104@?',
 'U12072@DOM9',
 'U3247@?',
 'U11926@DOM1',
 'ANONYMOUS LOGON@C17935',
 'ANONYMOUS LOGON@C6387',
 'SYSTEM@C18498',
 'U1427@DOM1',
 'ANONYMOUS LOGON@C4464',
 'U6101@DOM9',
 'ANONYMOUS LOGON@C16277',
 'C1670$@DOM1',
 'ANONYMOUS LOGON@C3653',
 'C5649$@?',
 'C10396$@?',
 'ANONYMOUS LOGON@C9718',
 ...]

In [12]:
# Adding user types
df = df.with_columns(pl.when(pl.col('source_user@domain').str.contains(r'^U\d+@')).then(pl.lit('human'))
          .when(pl.col('source_user@domain').str.contains(r'^C\d+\$@')).then(pl.lit('machine'))
          .when(pl.col('source_user@domain').str.contains(r'^(SYSTEM|LOCAL SERVICE|NETWORK SERVICE)@')).then(pl.lit('system'))
          .when(pl.col('source_user@domain').str.contains(r'^ANONYMOUS LOGON@')).then(pl.lit('anon'))
          .otherwise(pl.lit('other'))
          .alias('source_user_type'))

df = df.with_columns(pl.when(pl.col('destination_user@domain').str.contains(r'^U\d+@')).then(pl.lit('human'))
          .when(pl.col('destination_user@domain').str.contains(r'^C\d+\$@')).then(pl.lit('machine'))
          .when(pl.col('destination_user@domain').str.contains(r'^(SYSTEM|LOCAL SERVICE|NETWORK SERVICE)@')).then(pl.lit('system'))
          .when(pl.col('destination_user@domain').str.contains(r'^ANONYMOUS LOGON@')).then(pl.lit('anon'))
          .otherwise(pl.lit('other'))
          .alias('destination_user_type'))

In [ ]:
# Have managed to sucessfully capture all users with regexp
df.filter((pl.col('source_user@domain') == 'other') | (pl.col('destination_user@domain') == 'other')).collect()

shape: (0, 11)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ time ┆ source_use ┆ destinatio ┆ source_com ┆ … ┆ authentica ┆ success/f ┆ source_us ┆ destinati │
│ ---  ┆ r@domain   ┆ n_user@dom ┆ puter      ┆   ┆ tion_orien ┆ ailure    ┆ er_type   ┆ on_user_t │
│ str  ┆ ---        ┆ ain        ┆ ---        ┆   ┆ tation     ┆ ---       ┆ ---       ┆ ype       │
│      ┆ str        ┆ ---        ┆ str        ┆   ┆ ---        ┆ str       ┆ str       ┆ ---       │
│      ┆            ┆ str        ┆            ┆   ┆ str        ┆           ┆           ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

### Noteworthy findings

#### Section 1
No duplicates found


Clear distinction between human and machine users in the dataframe dermakated by $
Clear periodic behaviour observed for some machine users
Multiple requests made within identical time periods common

#### Example of clearly regular machine behaviour

![Output plot](savedplots/machine_plot1.png)
![Output plot](savedplots/machine_plot2.png)

### Typical examples of human behaviour
Less regularity is typically observed

![Output plot](savedplots/human_user1.png)
![Output plot](savedplots/human_user2.png)

### A note on domains, machines and system processes

Domains are basically big databases of usernames and passwords and permissions on a windows server. You authenticate against the domain and then are granted permissions to do stuff by the domain controler.

User activity is usually run with a user account. 

Computer accounts also exist and can be used by appications for running processes automated and not.

Windows also provides some built in accounts which can be harnessed by applications. These are the system accounts the domain here is the machine the system account is running on.

Anonymous logons are sessions where Windows did not associate the connection with a named authenticated identity. The underlying actor could be a user process, machine process, system process, or misconfigured service.

#### A note on source and destination users and machines

- source user = who you are coming from
- destination user = who you are logging/logging off in as
- source computer = where the login/logoff request comes from
- destination computer = where you are logging in /logging off too, e.g. accessing a file on a server requires you to authenticate onto a different machine

### Cleaning + Pipeline to do

- Filter the anon users as these can correspond to many different types of behaviour
- Maybe filter the system users out too
- Operate on a user not a computer level as multiple different users can share the same machine making messy behaviour on a machine level with mixture between human and machine time series observed.
- For each user, we estimate a mean and variance for every bin. These estimates are then smoothed towards cluster-average values. We first sort each user’s bin-level parameters to form a user-specific distribution. We then build a cluster-level reference distribution by averaging parameters at the same sorted position across users in the cluster. Each user’s parameter is then smoothed towards the corresponding value in this cluster distribution.